# This workflow builds and tests the portfolio app on push or pull request to the 'main' branch
name: Build and Test Portfolio App

# Trigger the workflow on push to 'main' or pull requests to 'main'
on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the 'main' branch

jobs:
  build:
    # Specify the environment for the job (latest Ubuntu)
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2
      # This step pulls the code to the GitHub runner

    # Step 2: Set up Python 3.8
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Use Python 3.8 for the project

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install the necessary packages

    # Step 4: Run the tests with pytest
    - name: Run tests
      run: |
        pytest  # Execute tests with pytest
        # If any test fails, the workflow will fail
